### ISSUE TITLE
Is it possible to extend the retention period to 2 years?

### ISSUE THREAD

**Issue by vrundaadhvaryu** [microsoft/PowerVirtualAgentsSamples#110]
Hello, my concern is that I want the summary analytics data for chatbot to be retained for upto 2 years to adhere to company policies, I contacted Microsoft Support to check if there is a way to customize the date settings when I came across this PoerBI dashboard. I can see the maximum it can go back to is 2 months, is it possible to change the settings or maybe change some query to get that data as far back to 2 years?
Thanks in advance!
<img width="822" alt="PowerBIPVA" src="https://user-images.githubusercontent.com/77395198/228293953-d92200ac-9985-4203-ac62-b4dfd12bd65a.PNG">

**Comment by luislera** [comment]
Hi @vrundaadhvaryu 

You can follow these steps to increase the date slider range up to 2 years from now.
1.	Open the Power BI template
2.	Locate and edit the `date` measure included in the `dates` table
 
![imagen](https://user-images.githubusercontent.com/62261539/232116098-6ebe427e-62df-411f-b794-cab7f2f2ee52.png)

3.	Update the measure using the following formula: `CALENDAR (DATE(YEAR(NOW())-2, MONTH(NOW()), DAY(NOW())), NOW())`
4.	Save the formula
 
![imagen](https://user-images.githubusercontent.com/62261539/232116150-e258083c-e539-4c67-9d60-d8b1c9127dc4.png)

After applying this change, the date slider should reflect 2 years from the current date.

![imagen](https://user-images.githubusercontent.com/62261539/232116212-f8276b62-f536-45c0-884f-7c36d8322648.png)

**Comment by iMicknl** [comment]
@vrundaadhvaryu do you connect directly to Dataverse or do you store your the transcript data for longer term on a datalake like ADLSgen2 (Azure Storage)?
