### ISSUE TITLE
Column 'botid' in Table 'bots' contains a duplicate value

### ISSUE THREAD

**Issue by Ruchikagarg2011** [microsoft/PowerVirtualAgentsSamples#130]
I am getting this error when I try to import the file on power BI.
Also when I check the bot table in my org it has two two chatbots with different bot id. Not sure why it is throwing error for duplicate values.

**Comment by nicolelynn4182** [comment]
I am having the same issue.

**Comment by HenryJammes** [comment]
Hi, I've published a version of the template that fixes that issue: https://github.com/microsoft/PowerVirtualAgentsSamples/blob/master/CustomAnalytics/PVA_Dashboard%20v1.1.pbit
