### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by jashok900061** [microsoft/PowerVirtualAgentsSamples#141]
Microsoft SQL: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)

how to resolve this error

**Comment by HenryJammes** [comment]
Hi @jashok900061
Can you provide more feedback on the context where you got this error?

**Comment by msravanthi674** [comment]
Yes 
Would like to know more about the error..

**Comment by jashok900061** [comment]
When Iam trying to import the data from dataverse to powerBI desktop i.e opening it from custom pva dashboard .pbit file for custom analytics

**Comment by HenryJammes** [comment]
I see, thank you. The template uses the Dataverse TDS endpoint, and this requires either port 5558 or 1433 to be opened on your network. See more on this error message here: https://learn.microsoft.com/en-us/power-apps/developer/data-platform/dataverse-sql-query#blocked-ports
