### ISSUE TITLE
I got error Environment variable AZURE_STORAGE_ACCOUNT_KEY must be set

### ISSUE THREAD

**Issue by smaciasMVP** [microsoft/PowerVirtualAgentsSamples#19]
For me is not clear what means /web/.env, I tried to create a file name process.env with the values you recommend but I sill get the error
![VAError](https://user-images.githubusercontent.com/7494102/80045906-789e6f80-84ce-11ea-8d4b-09ca0dc6e530.jpg)

**Comment by iMicknl** [comment]
The file should be named `.env`, not `process.env`, and should be placed in the `web` folder.

`/web/.env` is the full path.

**Comment by smaciasMVP** [comment]
Thanks Mick, sorry if I do not understand, I did everything on this post and it went good, but the file is the issue, when I try to create a file without a name windows gives me an error
![ErrorEnv](https://user-images.githubusercontent.com/7494102/81347510-ee373d80-9081-11ea-8c80-7dbb7c1a367c.jpg)

**Comment by smaciasMVP** [comment]
Someone told me that we nned to create the file using .net core so we can create with no error from windows. hope this help others
