### ISSUE TITLE
SSO configuration

### ISSUE THREAD

**Issue by StaubOliver** [microsoft/PowerVirtualAgentsSamples#27]
Hello, 
we are struggling to configure SSO (with AAD authentification) with PVA
We followed these documentations
https://docs.microsoft.com/en-us/power-virtual-agents/configuration-end-user-authentication
https://docs.microsoft.com/en-us/power-virtual-agents/configure-sso

the conversations starts and the auth card is handled by the javascript code (we also tried the sample from this repo)
PVA always gives an authentification error and the user cannot proceed to the conversation

Can you give us some insight about what might be wrong ?
We don't have any error in the browser itsleft as it appears to be generated by PVA's backend itself

Any help would be greatly appreaciated
Thanks

**Comment by aksridhar** [comment]
I also tried to fix some issues with above js files and the bot does show up but it always prompt for login. I am trying to embed this in SharePoint Online site where the user is already authenticated. I tried hardcoding the user email as well. But it always prompts for login screen. Once logged in, the bots works as expected. Buit seems like SSO is not working. Just want to let you know that I am trying to embed the PVA on Teams as well as SharePoint site and hence configured AAD V2. Any help will be appreciated

Thanks,
Sridhar Kandadai
