### ISSUE TITLE
Server URL not working for PVAs running inside a dataverser for teams

### ISSUE THREAD

**Issue by rjgmail88** [microsoft/PowerVirtualAgentsSamples#41]
I have PVA bot built in Team which leverages dataverser for teams. ( this is different than building PVA on powerva.microsoft.com which leverages dedicated dataverser environment )

I am following Installation steps [here ](https://github.com/microsoft/PowerVirtualAgentsSamples/tree/master/CustomAnalytics#installation-steps) where I server url associated with your Dataverse environment is not working form. I am not getting logged on to Teams dataverser.

![Screen Shot 2021-05-17 at 12 33 48 PM](https://user-images.githubusercontent.com/32375467/118532035-226d2180-b70c-11eb-9ad2-3dc23a6ebd4f.png)

Is there anyway to get this working? Or may be I'm not having correct URL to my Team dataverser?

**Comment by HenryJammes** [comment]
The PVA custom analytics reports can't work with PVA for Teams as this version doesn't store conversation transcripts in Dataverse.
