### ISSUE TITLE
several errors: data wont pull thur from dataverse

### ISSUE THREAD

**Issue by kat987654321** [microsoft/PowerVirtualAgentsSamples#71]
Hello, 

encountered several errors after trying to input the link of dataverse (removed the "https://: and the "/" -still errors, provided the attachment of the several errors found
- TDS is enable
- what else needs to be enables for the connection from dataverse to work ?

[errors.docx](https://github.com/microsoft/PowerVirtualAgentsSamples/files/7993187/errors.docx)
d

**Comment by iMicknl** [comment]
```
Microsoft SQL: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
```

See https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-powerbi-connector#error-message-unable-to-connect-provider-named-pipes-provider-error-40--could-not-open-a-connection-to-sql-server

> To use the Dataverse connector, TCP ports 1433 and/or 5558 need to be open to connect. If only port 5558 is enabled, you must append that port number to the Dataverse environment URL, such as yourenvironmentid.crm.dynamics.com:5558.

In my experience, corporate networks and VPN's can be a reason for not being able to connect.
