### ISSUE TITLE
Only first topic appearing in Topics page

### ISSUE THREAD

**Issue by philglew** [microsoft/PowerVirtualAgentsSamples#72]
Hi, 

I am using the basic version of this PBIT to visualise the chatbot data. In my chatbot, the user is directed to topics based on button selections, but there are no word triggers for those topics.

When a user uses the chatbot, only the first topic of "Greeting" is displayed and none of the other topics. How do I fix this so that all topics appear?

Thanks, 
Phil

**Comment by HenryJammes** [comment]
This is a known gap of the template and PVA analytics dashboards.
We're looking at improving this in an upcoming version.
